"""
simulate_validation.py

Generates a SIMULATED VALIDATION dataset: synthetic interaction records for
a small set of clearly hypothetical tester personas, used to demonstrate what
a validation study and its analysis would look like.

THIS IS NOT REAL USER TESTING. No real person performed these tasks or gave
these responses. Personas and response tendencies are authored to be
plausible; the numeric responses are generated by a seeded random process
described below, not invented ad hoc. See docs/validation-approach.md and
docs/simulated-validation-study.md for the full framing and analysis.

Usage:
    python src/simulate_validation.py

Output:
    data/simulated_validation_data.csv
"""

import csv
import random
from pathlib import Path

RANDOM_SEED = 7

# Each persona is a HYPOTHETICAL profile, not a real tester. "bias" values
# are the persona's typical (mean) rating on a 1-5 Likert scale for each
# measure; actual simulated values are drawn from a small distribution
# around that mean, then clipped to the valid 1-5 range. This keeps the
# output varied and traceable to a documented process rather than fixed
# numbers chosen by hand.
PERSONAS = [
    {
        "persona_id": "P1",
        "name": "Rushed Professional (hypothetical)",
        "description": "Office worker on a lunch break, low patience, values speed over detail.",
        "bias": {"ease_of_use": 4.2, "clarity": 3.8, "usefulness": 4.6, "trust": 3.0, "willingness_to_use": 4.0},
        "task_success_prob": 0.9,
    },
    {
        "persona_id": "P2",
        "name": "Budget-Conscious Student (hypothetical)",
        "description": "College student, comfortable with apps, wants to plan around class timing.",
        "bias": {"ease_of_use": 4.6, "clarity": 4.4, "usefulness": 4.2, "trust": 3.8, "willingness_to_use": 4.5},
        "task_success_prob": 0.95,
    },
    {
        "persona_id": "P3",
        "name": "Cautious Parent (hypothetical)",
        "description": "Handling a child's warranty claim, lower tech familiarity, wants reassurance.",
        "bias": {"ease_of_use": 3.2, "clarity": 3.0, "usefulness": 3.6, "trust": 3.2, "willingness_to_use": 3.0},
        "task_success_prob": 0.75,
    },
    {
        "persona_id": "P4",
        "name": "Skeptical Repeat Customer (hypothetical)",
        "description": "Has used the shop before without a prediction tool; doubts a system can estimate this well.",
        "bias": {"ease_of_use": 4.0, "clarity": 3.8, "usefulness": 3.2, "trust": 2.4, "willingness_to_use": 2.8},
        "task_success_prob": 0.85,
    },
    {
        "persona_id": "P5",
        "name": "First-Time Warranty Claimant (hypothetical)",
        "description": "Unfamiliar with the warranty repair process, wants terms explained clearly.",
        "bias": {"ease_of_use": 3.4, "clarity": 3.8, "usefulness": 4.0, "trust": 3.6, "willingness_to_use": 3.8},
        "task_success_prob": 0.8,
    },
]

MEASURES = ["ease_of_use", "clarity", "usefulness", "trust", "willingness_to_use"]


def simulate_measure(rng: random.Random, mean: float) -> int:
    value = rng.gauss(mean, 0.6)
    return max(1, min(5, round(value)))


def simulate_persona_row(rng: random.Random, persona: dict) -> dict:
    row = {
        "persona_id": persona["persona_id"],
        "persona_name": persona["name"],
    }
    for measure in MEASURES:
        row[measure] = simulate_measure(rng, persona["bias"][measure])

    row["task_success"] = rng.random() < persona["task_success_prob"]
    # Synthetic "time to understand the estimate", in seconds — loosely
    # informed by ease_of_use (easier -> faster), plus noise.
    base_seconds = 45 - (row["ease_of_use"] - 3) * 6
    row["time_to_understand_seconds"] = max(10, round(base_seconds + rng.gauss(0, 8)))
    return row


def main():
    rng = random.Random(RANDOM_SEED)
    rows = [simulate_persona_row(rng, p) for p in PERSONAS]

    out_path = Path(__file__).resolve().parent.parent / "data" / "simulated_validation_data.csv"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = list(rows[0].keys())
    with out_path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"Wrote {len(rows)} SIMULATED persona interaction rows to {out_path}")
    print("THIS IS SIMULATED DATA — no real users were involved.")


if __name__ == "__main__":
    main()
